import type { ScanResult } from '@/engine/types'

interface ReportLayoutProps {
  result: ScanResult
}

export default function ReportLayout({ result }: ReportLayoutProps) {
  const score = result.score
  const grade = score >= 90 ? 'A' : score >= 75 ? 'B' : score >= 50 ? 'C' : score >= 25 ? 'D' : 'F'
  const scoreColor = score >= 75 ? '#16a34a' : score >= 50 ? '#d97706' : '#dc2626'

  const scannedDate = new Date(result.scannedAt).toLocaleString()

  return (
    <div id="print-report" style={{ display: 'none' }}>
      {/* Header */}
      <div className="print-section">
        <h1>A11y Accessibility Report</h1>
        <h2>Web Accessibility Scanner — WCAG 2.1</h2>
        <table>
          <tbody>
            <tr>
              <th style={{ width: '120px' }}>URL</th>
              <td>{result.url}</td>
            </tr>
            <tr>
              <th>Scan Time</th>
              <td>{scannedDate}</td>
            </tr>
            <tr>
              <th>Duration</th>
              <td>{result.durationMs}ms</td>
            </tr>
            {result.fetchStrategy && (
              <tr>
                <th>Method</th>
                <td>{result.fetchStrategy}</td>
              </tr>
            )}
          </tbody>
        </table>
      </div>

      {/* Score Section */}
      <div className="print-section">
        <h2>Overall Score</h2>
        <table>
          <tbody>
            <tr>
              <td style={{ textAlign: 'center', padding: '20px' }}>
                <span className="print-score" style={{ color: scoreColor }}>
                  {score}
                </span>
                <span style={{ fontSize: '14pt', color: '#666' }}>/100</span>
                <div style={{ marginTop: '8px' }}>
                  <span className="print-grade" style={{ background: `${scoreColor}20`, color: scoreColor }}>
                    Grade {grade}
                  </span>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
        <table style={{ marginTop: '12px' }}>
          <thead>
            <tr>
              <th>Errors</th>
              <th>Warnings</th>
              <th>Info</th>
              <th>Total Issues</th>
            </tr>
          </thead>
          <tbody>
            <tr style={{ textAlign: 'center' }}>
              <td style={{ color: '#dc2626', fontWeight: 'bold', fontSize: '14pt' }}>{result.errors}</td>
              <td style={{ color: '#d97706', fontWeight: 'bold', fontSize: '14pt' }}>{result.warnings}</td>
              <td style={{ color: '#0284c7', fontWeight: 'bold', fontSize: '14pt' }}>{result.infos}</td>
              <td style={{ fontWeight: 'bold', fontSize: '14pt' }}>{result.totalIssues}</td>
            </tr>
          </tbody>
        </table>
      </div>

      {/* Issues Detail */}
      <div className="print-section print-page-break">
        <h2>Detailed Issues ({result.issues.length})</h2>
        {result.issues.length === 0 && (
          <p style={{ textAlign: 'center', padding: '20px', color: '#16a34a', fontWeight: 'bold' }}>
            No accessibility issues found. This page meets WCAG 2.1 standards.
          </p>
        )}
        {result.issues.map((issue, i) => (
          <div key={i} className="print-issue-row">
            <h3>
              {i + 1}. {issue.title}
            </h3>
            <div style={{ marginBottom: '8px' }}>
              <span className={`print-badge print-badge-${issue.level}`}>
                {issue.level.toUpperCase()}
              </span>
              <span className="print-badge print-badge-wcag">
                WCAG {issue.wcagLevel}
              </span>
              {issue.wcagCriteria.map((criteria) => (
                <span key={criteria} className="print-badge print-badge-wcag">
                  {criteria}
                </span>
              ))}
              <span style={{ fontSize: '9pt', color: '#888' }}>
                Rule: {issue.ruleId}
              </span>
            </div>
            <p style={{ marginBottom: '6px' }}>{issue.description}</p>
            {issue.elementHtml && (
              <div style={{ marginBottom: '6px' }}>
                <strong style={{ fontSize: '10pt', color: '#555' }}>Element:</strong>
                <code className="print-code">{issue.elementHtml}</code>
              </div>
            )}
            {issue.recommendation && (
              <div>
                <strong style={{ fontSize: '10pt', color: '#16a34a' }}>Recommendation:</strong>
                <p style={{ marginLeft: '12px', fontStyle: 'italic' }}>{issue.recommendation}</p>
              </div>
            )}
          </div>
        ))}
      </div>

      {/* Footer */}
      <div className="print-footer">
        <p>Generated by A11y Analyzer — Based on WCAG 2.1 Guidelines</p>
        <p>{scannedDate}</p>
      </div>
    </div>
  )
}
